### ISSUE TITLE
Why the generated code doesn't generates TS enums?

### ISSUE THREAD

**Issue by bennyk8y** [remorses/genql#119]
Is there's a way to generate TS enum instead of string literals unions?
Looks like there's not, is there a specific reason behind it?

**Comment by remorses** [comment]
Genql uses literal enums because Typescript enums rely on runtime code and [are considered harmful](https://dev.to/ivanzm123/dont-use-enums-in-typescript-they-are-very-dangerous-57bh#:~:text=ENUMs%20may%20seem%20like%20a,opt%20for%20objects%20or%20types.)

To use an enum value at runtime you can import the value `enumX` where `X` is the enum type
