### ISSUE TITLE
Does genql support watching directories for changes to gen code?

### ISSUE THREAD

**Issue by patrickphat** [remorses/genql#121]
Does genql support watching directories for changes to gen code? I see that [graphql code generator](https://the-guild.dev/graphql/codegen) support `--watch` in their CLI for watching code changes

**Comment by Julien-R44** [comment]
it's not really comparable. Graphql-code-generator allows you to watch the files because they generate the typings according to the queries you write in your codebase. 

With Genql you don't need to do that. All necessary types are generated from the beginning, you don't need to regenerate anything when you write a new query. 
You just have to regenerate genql typings when your underlying graphql schema changes.
