### ISSUE TITLE
Optional fields are not defined as optional properties

### ISSUE THREAD

**Issue by dhmacs** [remorses/genql#14]
GraphQL types that are optional are converted to typescript like this:

```typescript
board: (board|null)
```
This forces you to define all fields in a request, even if they are not required e.g.
```typescript
{
  board: null
}
```

IMO, optional GraphQL fields should be typed like [optional properties](https://www.typescriptlang.org/docs/handbook/interfaces.html#optional-properties) so that you can avoid verbose code

**Comment by remorses** [comment]
Yes, it would be better, even if the spec says optional fields will be set to null, in JavaScript there is really no change between null and undefined

**Comment by dhmacs** [comment]
Yes I have the latest version. Btw I'm referring to response types. We do a lot of optimistic updates therefore we need to write on the cache, and it's quite verbose having to set all field as nulls

**Comment by remorses** [comment]
I changed the types to be more similar to graphql code generator and improved the overall typings

One thing that I am unable to improve is type validation for additional fields in the query request object, this is because of this line

```ts
type query = <R extends QueryRequest>(request: R) => Promise<...>
```

The generic R extends Query and in typescript a generic that extends a type T can have additional fields not present in T, do you know any solution for this?

**Comment by dhmacs** [comment]
I need to dive deep into this to come up with something. For now I postponed the refactoring of the part of code that causes trouble with typings. Soon I'll have to get back to it and I'll let you know
