### ISSUE TITLE
Fix code example copy/paste in docs

### ISSUE THREAD

**Issue by DavidWells** [remorses/genql#34]
Hello there. Very cool project!

I noticed something in the docs that breaks copy/paste. When highlighting code the line numbers are also copied

![image](https://user-images.githubusercontent.com/532272/94591906-8bfff480-023d-11eb-8b83-4dcbb3ba1c19.png)

If you add this one CSS rule `user-select: "none;"` this will fix itself. 

After with `user-select` none on those numbers

![image](https://user-images.githubusercontent.com/532272/94591947-9d490100-023d-11eb-83c4-38caef3cf465.png)

I wasn't able to find where this style is generated to fix myself 😅

**Comment by remorses** [comment]
Thank you for opening an issue

I am already aware of this problem, but i still need to update a dependency for the fix

However the user select fix will not work on safari because why not

If you want to take a look at the code the website code is from a general documentation site generator I made at https://github.com/remorses/dokz

**Comment by remorses** [comment]
This is now fixed in latest docs using chrome
