### ISSUE TITLE
Null instead of Undefined

### ISSUE THREAD

**Issue by Maxvien** [remorses/genql#36]
This is the `image` field in Shema.
![image](https://user-images.githubusercontent.com/1142799/95305121-c3ab1400-08af-11eb-8329-dce70566cdcb.png)

This is the `image` field which is generated by `genql`. It must be `null`, not `undefined`. Do you have an option to config it? 

See also: https://github.com/graphql/graphql-js/issues/1298#issuecomment-377365916

![image](https://user-images.githubusercontent.com/1142799/95409786-a415f900-094c-11eb-918e-68633e510a54.png)

#### tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```
Now I have to use this function to convert `null` to `undefined`:

```js
import traverse from 'traverse';

function nullToUndefined<D extends any>(data: D) {
  return traverse(data).map(function (value) {
    if (value === null) this.update(undefined);
  }) as D;
}
```

**Comment by remorses** [comment]
Can you show me your use case? where are you using `nullToUndefined`?

**Comment by Maxvien** [comment]
@remorses You can check it here:

```ts
import traverse from "traverse";
import { createClient } from "./generated";

function nullToUndefined<D extends any>(data: D) {
  return traverse(data).map(function (value) {
    return value === null ? this.update(undefined) : this.update(value);
  }) as D;
}

const client = createClient();

(async () => {
  const data = await client.query({
    users: {
      email: true,
      image: true,
    },
  });

  const { users } = nullToUndefined(data);

  const { image } = users[0]; // const image: string | undefined
})();

```

**Comment by remorses** [comment]
I used undefined to simplify the typescript types, tell me if you find any problem where null should be used instead

**Comment by nullndr** [comment]
Hey @remorses, I have a use case where `null` should be used instead of `undefined`.

I have the entity customer from Shopify that is primary parsed via webhooks, where I have some fields as `null`.

I also have to retrieve some data from orders ecc, but the two are incompatible since the types from JSON rest is `string | null` while the types from genql is `string | undefined`.

Until now, I simply use the `??` operator to transform `undefined` values into `null`, but I don't like this, since I should be able to just use `null`, here an example:

```ts
await processAutomations.queue.add(
  "process automations of type ORDER_CONFIRMATION",
  {
    customer: {
      admin_graphql_api_id: customer.id,
      created_at: customer.createdAt,
      email: customer.email ?? null,
      first_name: customer.firstName ?? null,
      last_name: customer.lastName ?? null,
      phone: customer.phone ?? null,
      tags: customer.tags,
      updated_at: customer.updatedAt,
      sms_marketing_consent:
        smsMarketingConsent == null
        ? null
        : {
          state: smsMarketingConsent.marketingState,
          consent_updated_at:
            smsMarketingConsent.consentUpdatedAt ?? null,
          consent_collected_from:
            smsMarketingConsent.consentCollectedFrom ?? null,
      },
      default_address: {
        country,
        country_code: countryCodeV2,
      },
    },
    type: "ORDER_CONFIRMATION",
    shopifyDomain,
  },
);
```

I understand that `undefined` helps you with typescript types, but I really can't see why I (as a library client) should have a mismatched type.

**Comment by RobbeCl** [comment]
Why is this closed? There is a mismatch between the types and what graphql returns.

**Comment by remorses** [comment]
i will add `null` to the types soon

**Comment by ayoung19** [comment]
hey @remorses, we've ran into the same problem for mutations where we base the mutation inputs on the return of a graphql query (where null sets it as null and undefined doesn't change the field at all).

is there an eta on this behavior, would you like some help with it?

**Comment by remorses** [comment]
Released in `4.0.0`

**Comment by ayoung19** [comment]
@remorses this is awesome! thank you so much this is a huge win for our use case.

however i think there's a small bug and response fields are still incorrectly typed as undefinable with `?`. i think request fields should definitely keep that behavior though because `undefined` represents opting out of mutating the field and leaving it unchanged (`Optional` on a python backend) while `null` actually sets it to NULL on the database (`None` on a python backend). however a query should never respond with undefined

<img width="431" alt="image" src="https://user-images.githubusercontent.com/18640252/234060385-00507ad9-389d-4ec1-a6b5-93b6a2cb5ef9.png">
 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/18640252/234060454-9ab4d6ee-1479-4b99-b339-8801aba4e79d.png">

**Comment by remorses** [comment]
If you want to remove the undefined values from a type simply use `Required<Type>`

I don't want to remove undefined from the response fields, it makes much easier to reuse types, for example

```ts

let repository: Repository = {
  name: 'x'
}
```

instead of 

```
let repository: Repository = {
  name: 'x',
  anotherField: null,
  someOtherField: null,
  // ...
}
```

**Comment by ayoung19** [comment]
hm great suggestions with `Required`, but it doesn't really recurse well unless we write another helper.

what's the problem with removing undefined from response fields? i don't see what's wrong with the latter if that's the return of an endpoint.

**Comment by remorses** [comment]
@ayoung19 can you show me an example where having `undefined` in type type is a problem?

**Comment by ayoung19** [comment]
well the core problem is the type returned by graphql is null, not undefined. we've actually ran into bugs where we tried to destruct an incoming object and assign a default value to an incoming object from our backend which typescript would incorrectly let us do, something like this:

```
const { name = 'John Doe' } = person;
name.split(' '); // runtime error, person.name is null even though it's typed as string | undefined
```

beyond that, we also have form state code that looks like what @nullndr posted, we have to add `|| null` to all of the incoming fields so that they are properly typed as `null`, so on mutations we can send the object back. we can't store it as `undefined` because `undefined` means opt out of changes in the mutation input

**Comment by remorses** [comment]
I ended up removing the undefined types in version 5
