### ISSUE TITLE
Wrong types in results when using fragment syntax

### ISSUE THREAD

**Issue by MichalLytek** [remorses/genql#61]
I have generated SDK for Shopify Admin API and I see some issues with the type of the response.

When I do not request common interface fields, only the one from fragment (selected type - `CustomerVisit`), in the response I get all the fields, thus I can try to access them but they will always be undefined so my app will work incorrectly:

![image](https://user-images.githubusercontent.com/10618781/128172679-41bf2860-c47d-4b1e-85cc-c84048f6f8eb.png)

However, for the leaves, scalars it works ok, both inside the fragment and for the other properties:

![image](https://user-images.githubusercontent.com/10618781/128172547-580b076d-9020-4460-88e2-bc4495922ff9.png)

**Comment by remorses** [comment]
The problem here is that node is an union or interface type, this means you can use any fields of the union even if you did not fetch it.

unfortunately this is a problem difficult to fix because it would increase the typings complexity by A LOT and also compile time with it

To work around this you can tell typescript what type you are expecting to see and allow only a subset of possible fields like in this example https://genql.vercel.app/docs/usage/unions-and-interfaces#restrict-an-union-to-the-correct-sub-type
