### ISSUE TITLE
Cannot access errors fields

### ISSUE THREAD

**Issue by Hulkmaster** [remorses/genql#95]
I receive graphql response from server, which contains
```
{
  data: { ... }
  errors: { ... }
}
```

and i need to access errors fields in order to understand what happened and what to show to user

and it seems like lib just transforms whole object into single string, startings with `errors.message`

is there a way to receive proper object back?

**Comment by kcammanabrolu** [comment]
I have the same issue. Not sure, why `ClientError` is serializing the downstream `error` and concatenating with `message`. Ideally I'd like to access the `originalError` from the downstream graphql server in order to handle it effectively in my code. Can you please suggest if there is any feature request already planned to redesign `ClientError`

**Comment by joeberetta** [comment]
U're guys absolutely right
As I got we have to write your own fetcher which implements [BaseFetcher](https://github.com/remorses/genql/blob/master/cli/src/runtime/client/createClient.ts#L14)

Cuz by default lib checks existence of `errors` field, concats it and throws exception. This part of code is [here](https://github.com/remorses/genql/blob/c3dfb773cfcb12d7a5be129fb405343c5a52447c/cli/src/runtime/fetcher.ts#L48)

**Comment by joeberetta** [comment]
By the way it duplicates #60

**Comment by remorses** [comment]
v3 is out with the fix, genql will throw a `GenqlError` with graphql errors ettached
